// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsAnalytics.Infrastructure.Data;

#nullable disable

namespace SportsAnalytics.Infrastructure.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20260725114641_AddArchiveFieldsToPrediction")]
    partial class AddArchiveFieldsToPrediction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("MatchDate");

                    b.HasIndex("HomeTeamId", "AwayTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.MatchStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayCorners")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayFouls")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AwayPossessionPct")
                        .HasColumnType("REAL");

                    b.Property<int>("AwayRedCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayShotsOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayShotsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayYellowCards")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DataQualityScore")
                        .HasColumnType("REAL");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeCorners")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeFouls")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HomePossessionPct")
                        .HasColumnType("REAL");

                    b.Property<int>("HomeRedCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeShotsOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeShotsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeYellowCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("MatchId1")
                        .IsUnique();

                    b.ToTable("MatchStatistics");
                });

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InjuryUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInjured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualAwayGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualHomeGoals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualResult")
                        .HasColumnType("TEXT");

                    b.Property<double>("AwayWinProbability")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DrawProbability")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeWinProbability")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LambdaAway")
                        .HasColumnType("REAL");

                    b.Property<double>("LambdaHome")
                        .HasColumnType("REAL");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("RiskScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MatchId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.Match", b =>
                {
                    b.HasOne("SportsAnalytics.Domain.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsAnalytics.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.MatchStatistics", b =>
                {
                    b.HasOne("SportsAnalytics.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsAnalytics.Domain.Entities.Match", null)
                        .WithOne("Statistics")
                        .HasForeignKey("SportsAnalytics.Domain.Entities.MatchStatistics", "MatchId1");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.Player", b =>
                {
                    b.HasOne("SportsAnalytics.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("SportsAnalytics.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("SportsAnalytics.Domain.Entities.Match", b =>
                {
                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
